### ISSUE TITLE
Fix logo, version, links on Che dashboard

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-che#11]
On the bottom of the Che 7.3.1 dashboard, 
- The Kabanero logo is next to Che version 7.3.1 which can be mistaken as Kabanero version (_see screen capture below_).  Should we have the Kabanero logo here?
- Docs and Support buttons are both pointing to  https://kabanero.io/ , should they be pointing to Che doc and support?

![image](https://user-images.githubusercontent.com/22480038/68967950-fdaa8d80-07a6-11ea-9691-8ea31c6b383d.png)

**Comment by makandre** [comment]
<img width="316" alt="image" src="https://user-images.githubusercontent.com/17596240/69065789-456f2600-09ee-11ea-9fbe-715105891104.png">

I assume Docs should point to https://kabanero.io/docs

We actually have more control over what the second button can be.  For default Che, the link is [Community](https://www.eclipse.org/che/).  In my screenshot above, I tested setting it to [Guides](https://kabanero.io/guides/)

@tam512 Any preference on what that second button should be?

**Comment by makandre** [comment]
And it appears I can hide the version to avoid confusion about the version
